### ISSUE TITLE
modularized and rewrote

### ISSUE THREAD

**Issue by maxlath** [tadas-s/isbnjs#17]
hello! thank you for this project!
I was having trouble with an invalid ISBN, so I started [playing with your code](https://github.com/maxlath/isbnjs) to understand how it works, modularizing and rewriting as I like to better see through it, and ended up sort of rewriting a lot of things ^^

Among other things:

* I dropped the class architecture for something lighter, which [broke the API](https://github.com/maxlath/isbnjs#examples)
* modularized the code (but it could easily be re-bundled using [browserify](http://browserify.org))
* used ES6 syntax
* used [standardjs](https://github.com/feross/standard) as linter

Would you be interested in getting it, or part of it, merged in `isbn2`? Given the amount of changes, I was considering making it a `isbn3` module, but if that's of interest, we could spare the community another module doing pretty much the same thing. As you like :)

**Comment by tadas-s** [comment]
Hi @maxlath 

Sorry for late reply. I no longer work for the company which was interested in maintaining this library.

If you're not in a rush I'll take a look at this again this week.

**Comment by maxlath** [comment]
absolutely no rush :)

**Comment by maxlath** [comment]
fyi, we moved on to (yet another) fork, based on the principles of this PR: [isbn3](https://github.com/inventaire/isbn3)
