### ISSUE TITLE
Recent ISBN is not properly hyphenated

### ISSUE THREAD

**Issue by clemlatz** [tadas-s/isbnjs#7]
If have this recent french EAN : `9791091146135` that should converts, with hyphens, to : `979-10-91146-13-5`, but :

``` javascript
ISBN.parse(9791091146135).asIsbn13(true)
```

gives me `979-1-09-114613-5`

It think the problem may be that the new french prefix 979-10 is missing or that the lib may not handle recent 979- ISBNs at all.

**Comment by tadas-s** [comment]
Hi,

Python `isbntools` agrees with you:

```
$ isbn_mask 9791091146135
979-10-91146-13-5
```

And I cannot really say I've ever looked into how this library works. I mostly forked to make it compatible with nodejs + keep updating isbn group list.

**Comment by clemlatz** [comment]
I've successfuly modified the `mkgroups.pl` file to extract 979-\* groups and got this:

``` javascript
{
   10: {
    name: 'France',
    ranges: [
      ['00', '19'],
      ['200', '699'],
      ['7000', '8999'],
      ['90000', '97599'],
      ['976000', '999999']
    ]
  },
  11: {
    name: 'Korea, Republic',
    ranges: [
      ['00', '24'],
      ['250', '549'],
      ['5500', '8499'],
      ['85000', '94999'],
      ['950000', '999999']
    ]
  },
  12: {
    name: 'Italy',
    ranges: [
      ['200', '200']
    ]
  }
```

But I think there's changes to do in the `isbn.js` file as well. Would you accept a pull-request if i figure out how to do it?

**Comment by tadas-s** [comment]
Ah, now it makes sense. Absolutely. Feel free to open PR for `mkgroups.pl`. Updating group list after that is bit manual (involves copying and pasting and then undoing some unrelated changes), I can do it though.

Cheers!

**Comment by clemlatz** [comment]
I think it's more than just updating the group list in `isbn.js`, because now you'll have two different group lists to pick from (one for 978-\* and one for 979-\* ISBNs), but I'll start on the `mkgroups.pl` file (learning Perl, yay!)

**Comment by tadas-s** [comment]
Oh, OK. Anyway, good job and showing & explaining the issue. Yeah, it will be bit more involved.
